openapi: 3.0.3
info:
  title: CommitUpp API
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /groups:
    $ref: './group-create.yml'
  /user/callback:
    $ref: './user-login-callback.yml'
  /user/logout:
    $ref: './user-logout.yml'
  /movies:
    $ref: './movies.yml'
  /movie/status:
    $ref: './movie-status.yml'
  /groups/{group_id}/watched-movies:
    $ref: './group-watched-movies.yml'

components:
  securitySchemes:
    SupabaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateGroupRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50

    CreateGroupResponse:
      type: object
      required:
        - group
      properties:
        group:
          $ref: "#/components/schemas/Group"

    Group:
      type: object
      required:
        - id
        - name
        - monthlyGoal
        - createdAt
      properties:
        id:
          type: string
        name:
          type: string
        monthlyGoal:
          type: integer
          format: int32
          minimum: 0
        createdAt:
          type: string
          format: date-time

    LoginCallbackResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string

    LogoutResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string

    MoviesResponse:
      type: object
      required:
        - movies
      properties:
        movies:
          type: array
          items:
            $ref: '#/components/schemas/Movie'

    Movie:
      type: object
      required:
        - movie_id
        - tmdb_id
        - title
        - poster_url
      properties:
        movie_id:
          type: string
        tmdb_id:
          type: string
        title:
          type: string
        poster_url:
          type: string

    MovieStatusRequest:
      type: object
      required:
        - movie_id
        - status
      properties:
        movie_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [watched, wanna_watch]

    MovieStatusResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: success

    GetMovieStatus:
      type: object
      required:
        - movie_id
        - tmdb_id
        - title
        - poster_url
        - trailer_url
        - overview
        - release_date
        - updated_at
      properties:
        movie_id:
          type: string
        tmdb_id:
          type: string
        title:
          type: string
        poster_url:
          type: string
        trailer_url:
          type: string
        overview:
          type: string
        release_date:
          type: string
        updated_at:
          type: string
          format: date-time

    GetMovieStatusResponse:
      type: object
      required:
        - movies
      properties:
        movies:
          type: array
          items:
            $ref: "#/components/schemas/GetMovieStatus"

    GetGroupWatchedMoviesResponse:
      type: object
      required:
        - group_id
        - movies
      properties:
        group_id:
          type: string
        movies:
          type: array
          items:
            $ref: "#/components/schemas/GetGroupWatchedMoviesMovie"

    GetGroupWatchedMoviesMovie:
      type: object
      required:
        - movie_id
        - title
        - poster_url
        - watched_member
      properties:
        movie_id:
          type: string
        title:
          type: string
        poster_url:
          type: string
        watched_member:
          type: array
          items:
            $ref: "#/components/schemas/WatchedMember"

    WatchedMember:
      type: object
      required:
        - user_id
        - avatar_url
      properties:
        user_id:
          type: string
        avatar_url:
          type: string

    BadRequestError:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    ForbiddenError:
      type: object
      required:
        - message
      properties:
        message:
          type: string  

    UnauthorizedError:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    InternalServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
